In [2]:
import numpy as np
arr=np.random.randint(1,100,size=(3,4))

In [3]:
arr

array([[93, 63, 66,  3],
       [58, 14, 99, 79],
       [44, 71, 72, 95]])

In [4]:
#取多列
arr[1,[1,2]]
#取1，2列
arr[:,[1,2]]

array([14, 99])

In [6]:
#取多行
arr[[1,2],1]
#取1，2行
arr[[1,2],:]

array([14, 71])

In [8]:
#通过bool取数组里的值
bool_1=[True,True,False,False,False]
arr1=np.random.randint(1,34,size=(5))
arr1[bool_1]

array([26, 24])

In [9]:
#取多维
arr2=np.random.randint(1,55,size=(3,4))
arr2

array([[35, 19, 10,  4],
       [14, 23,  4,  3],
       [41, 25, 31, 18]])

In [10]:
#取行
bool_2=[True,True,False]
arr2[bool_2]

array([[35, 19, 10,  4],
       [14, 23,  4,  3]])

In [12]:
#取列
bool_2=[True,True,False,False]
arr2[:,bool_2]

array([[35, 19],
       [14, 23],
       [41, 25]])

In [38]:
#改变数组形状
arr2=arr2.reshape(4,3)


AttributeError: 'numpy.ndarray' object has no attribute 'detype'

In [33]:
#多行多列
arr

array([[93, 63, 66,  3],
       [58, 14, 99, 79],
       [44, 71, 72, 95]])

In [39]:
arr[[1,2]][:,[1,2]]
arr

array([[93, 63, 66,  3],
       [58, 14, 99, 79],
       [44, 71, 72, 95]])