In [6]:
import numpy as np
arr=np.random.randint(1,56,size=(3,4))
arr

array([[ 1, 30, 23, 23],
       [39, 31, 20, 53],
       [54, 14, 41, 47]])

In [7]:
#插入列
np.insert(arr,1,90,axis=1)

array([[ 1, 90, 30, 23, 23],
       [39, 90, 31, 20, 53],
       [54, 90, 14, 41, 47]])

In [10]:
np.insert(arr,1,[89,89,89],axis=1)

array([[ 1, 89, 30, 23, 23],
       [39, 89, 31, 20, 53],
       [54, 89, 14, 41, 47]])

In [8]:
arr

array([[ 1, 30, 23, 23],
       [39, 31, 20, 53],
       [54, 14, 41, 47]])

In [9]:
#插入行
np.insert(arr,1,90,axis=0)

array([[ 1, 30, 23, 23],
       [90, 90, 90, 90],
       [39, 31, 20, 53],
       [54, 14, 41, 47]])

In [27]:
#在末尾添加元素 行
np.append(arr,[[89,23,90,90]],axis=0)

array([[ 1, 30, 23, 23],
       [39, 31, 20, 53],
       [54, 14, 41, 47],
       [89, 23, 90, 90]])

In [23]:
arr

array([[ 1, 30, 23, 23],
       [39, 31, 20, 53],
       [54, 14, 41, 47]])

In [28]:
#在末尾添加元素 列
np.append(arr,[[89],[34],[23]],axis=1)

array([[ 1, 30, 23, 23, 89],
       [39, 31, 20, 53, 34],
       [54, 14, 41, 47, 23]])

In [29]:
#删除
np.delete(arr,1,axis=1)

array([[ 1, 23, 23],
       [39, 20, 53],
       [54, 41, 47]])