In [1]:
import numpy as np


In [2]:
#两个数组相乘
arr=np.random.randint(1,10,size=(3,5))
arr1=np.random.randint(1,10,size=(5,3))
arr2=np.dot(arr,arr1)#数组相乘
display(arr,arr1,arr2)

array([[4, 9, 9, 7, 6],
       [4, 2, 3, 7, 6],
       [5, 9, 6, 1, 7]])

array([[5, 9, 5],
       [1, 4, 9],
       [9, 2, 1],
       [3, 5, 9],
       [2, 1, 3]])

array([[143, 131, 191],
       [ 82,  91, 122],
       [105, 105, 142]])

In [ ]:
#排序 sort
"""
numpy 中的sort  排序不影响自身
数组中的sort 排序影响自身
"""

In [47]:
#部分排序
# numpy.partition() 部分排序
a=np.random.permutation(100)#从零开始到指定数据 随机的生成的是指定数据的长度
a
 

array([10, 62,  6, 21,  2, 56, 25, 63, 41, 35, 76, 68, 90, 72, 67, 79, 29,
       36,  5, 86, 18, 42, 64, 60, 58, 81, 49, 47, 84, 26, 11, 23, 12, 13,
       48, 45, 31, 96,  4, 44, 30, 71, 37, 51,  1, 52, 61, 66, 39, 83, 46,
       53, 34, 65, 70, 43, 87, 59, 89, 78, 97, 27, 14, 91, 15, 74, 16, 24,
       17, 22, 33, 93, 20,  0, 77, 55, 50, 88, 38, 54, 73, 40,  9, 85,  8,
        3, 80, 19, 94, 99, 95, 69, 28, 57, 32, 98,  7, 82, 92, 75])

In [6]:
a.sort()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
"""
kth 
    如果是正数  获取前几个最小的数
    如果是负数  获取前几个最大的数   数据在数组后端
"""

'\nkth \n    如果是正数  获取前几个最小的数\n    如果是负数  获取前几个最大的数   数据在数组后端\n'

In [48]:
np.partition(a,-6)

array([55, 10,  6, 21,  2, 56, 25, 63, 41, 35,  7, 68, 32, 72, 67, 57, 29,
       36,  5, 28, 18, 42, 64, 60, 58, 69, 49, 47, 19, 26, 11, 23, 12, 13,
       48, 45, 31,  3,  4, 44, 30, 71, 37, 51,  1, 52, 61, 66, 39, 62, 46,
       53, 34, 65, 70, 43,  8, 59,  9, 40, 73, 27, 14, 54, 15, 74, 16, 24,
       17, 22, 33, 38, 20,  0, 50, 75, 80, 77, 82, 76, 79, 78, 81, 83, 86,
       84, 85, 87, 90, 89, 92, 93, 88, 91, 94, 98, 99, 96, 95, 97])

In [65]:
np.partition(a,6)

array([ 0,  1,  3,  4,  2,  5,  6,  7,  8,  9, 10, 11, 12, 19, 13, 17, 15,
       14, 20, 21, 18, 16, 22, 24, 28, 27, 23, 25, 26, 29, 30, 33, 32, 31,
       34, 45, 48, 47, 49, 44, 42, 36, 37, 40, 38, 35, 41, 43, 39, 46, 50,
       53, 62, 65, 70, 66, 61, 59, 52, 51, 73, 71, 69, 54, 58, 74, 60, 64,
       57, 67, 72, 68, 63, 56, 55, 75, 77, 88, 93, 91, 97, 78, 89, 85, 87,
       96, 80, 84, 94, 99, 95, 81, 86, 79, 90, 98, 76, 82, 92, 83])